[graph]
all-features = true

[advisories]
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception", # Used by target-lexicon (transient dep through pyo3)
    "BSD-2-Clause", # Used by arrayref
    "BSD-3-Clause", # Used by tiny-skia/tiny-skia-path
    "Zlib", # Used by const_format/const_format_proc_macros
    "Unicode-3.0", # Used by various icu4x crates, both direct and transient dependencies
]
confidence-threshold = 0.95
exceptions = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
skip = [
    { crate = "bitflags@1.3.2", reason = "tiny-skia uses older png, leading to this older transient dep" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = ["https://github.com/staticintlucas/keyset-rs"]
