repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-added-large-files
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
      args: ['--remove']
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: trailing-whitespace
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
    - id: isort
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    - id: black
      language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8

exclude: |
  (?x)(
    ^dist/|
    ^venv/|
    ^example/example.svg$
  )
