[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

[project]
name = "pykeyset"

[project.scripts]
pykeyset = "pykeyset.__main__:app"

[tool.black]
line-length = 100
target-version = ["py36", "py37", "py38", "py39"]

[tool.isort]
profile = "black"
multi_line_output = 3
