[tool.poetry]
name = "pykeyset"
version = "0.0.0"  # Placeholder for poetry-dynamic-versioning
description = """\
    A Python-based tool to create pretty keyset layout diagrams using correct fonts and icons."""
license = "MIT"
authors = ["Lucas Jansen <7199136+staticintlucas@users.noreply.github.com>"]
readme = "README.md"
repository = "https://github.com/staticintlucas/pykeyset"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Programming Language :: Python :: Implementation :: CPython",
    # TODO no PyPy support because recordclass fails to compile
    # "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.poetry.scripts]
pykeyset = "pykeyset.__main__:_start"

[tool.poetry.dependencies]
python = "^3.6"
colorama = "^0.4.3"
ansiwrap = "^0.8.2"
toml = "^0.10.1"
recordclass = "^0.14.0"
importlib-resources = { version="^4.0", python="<3.7" }

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.1.1"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
format-jinja = """\
    v{{ base }}\
    {% if stage is not none %}\
        -{{ stage }}{{ revision }}\
    {% endif %}\
    {% if distance > 0 or dirty %}\
        +{{ distance }}.g{{ commit }}\
    {% endif %}\
    {% if dirty %}\
        .dirty\
    {% endif %}"""

[tool.black]
line-length = 100
target-version = ["py36", "py37", "py38"]

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
